//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestShop.Model
{
    using System;
    using System.Collections.Generic;

    public partial class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> IdCategory { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public string IsAvaiableText
        {
            get
            {
                return IsAvailable ? "Да" : "Нет";
            }
        }
       public string Photo { get; set; }

        public virtual Category Category { get; set; }
    }
}
